#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

MUST_NOT_CHANGE='public/css/app.css'

if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=fe0c2d664e271c19a2c6f57c6515696b9f7f11c2
fi

exec 1>&2

if git diff --cached --name-only $against |
   grep --quiet --line-regexp --fixed-strings "$MUST_NOT_CHANGE"
then
  echo "El commit añadiría cambios a 'public/css/app.css'"
  echo "Por favor remuevelo de la fase de stage con 'git restore --staged public/css/app.css'\n"
  exit 1
else
  exit 0
fi
